# Generated by Django 5.1.4 on 2026-05-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_level_alter_student_level'),
        ('app_roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='level',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_auth.level'),
        ),
    ]
