# Generated by Django 5.1.4 on 2026-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roadmap', '0003_roadmap_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
