# Generated by Django 5.1.4 on 2026-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roadmap', '0004_submission_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
