# Generated by Django 5.1.4 on 2026-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roadmap', '0005_alter_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reaction',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
