# Generated by Django 5.1.4 on 2026-07-08 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guidance', '0001_initial'),
        ('app_roadmap', '0006_submission_reacted_at_submission_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_roadmap.submission'),
        ),
    ]
