# Generated by Django 5.1.4 on 2026-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guidance', '0002_message_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('submission', 'Submission')], default='text', max_length=20),
        ),
    ]
