# Generated by Django 5.1.4 on 2026-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('WEB', 'WEB'), ('CONTENT', 'CONTENT')], db_index=True, max_length=20)),
                ('section', models.CharField(blank=True, db_index=True, default='', help_text='Contoh: HEADER, ICON1, ROADMAP', max_length=50)),
                ('key', models.CharField(help_text='Nama key program', max_length=100)),
                ('label', models.CharField(help_text='Label yang tampil di Admin', max_length=100)),
                ('value', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='settings/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='settings/videos/')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('image', 'Image'), ('video', 'Video'), ('icon', 'Icon')], default='text', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'section', 'order', 'id'],
                'unique_together': {('group', 'section', 'key')},
            },
        ),
    ]
