# Generated by Django 5.1.4 on 2026-07-02 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_auth', '0003_user_last_seen'),
        ('app_roadmap', '0003_roadmap_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tracking Rule', max_length=100)),
                ('minimum_score', models.PositiveIntegerField(default=75)),
                ('day_to_evaluate', models.JSONField(blank=True, default=list)),
                ('time_to_evaluate', models.TimeField(blank=True, null=True)),
                ('day_to_serve', models.JSONField(blank=True, default=list)),
                ('time_to_serve', models.TimeField(blank=True, null=True)),
                ('day_to_correct', models.JSONField(blank=True, default=list)),
                ('time_to_correct', models.TimeField(blank=True, null=True)),
                ('limit_assignment', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foul_type', models.CharField(choices=[('ABSENT', 'Absent'), ('NOT_SUBMITTED', 'Not Submitted'), ('LOW_SCORE', 'Low Score'), ('LATE_SUBMISSION', 'Late Submission'), ('OTHER', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('overcome_type', models.CharField(choices=[('REMEDIAL', 'Remedial'), ('EXTRA_ASSIGNMENT', 'Extra Assignment'), ('REMINDER', 'Reminder'), ('COUNSELING', 'Counseling'), ('CALL_PARENT', 'Call Parent'), ('OTHER', 'Other')], max_length=30)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tracking/')),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fouls', to='app_roadmap.assignment')),
                ('refer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_fouls', to='app_roadmap.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.teacher')),
            ],
            options={
                'ordering': ['-schedule', '-created_at'],
            },
        ),
    ]
