# Generated by Django 5.1.4 on 2026-07-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='day_to_work',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rule',
            name='time_to_work',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
