# Generated by Django 5.1.4 on 2026-07-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracking', '0002_rule_day_to_work_rule_time_to_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='time_to_correct',
            new_name='end_time_to_correct',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='time_to_evaluate',
            new_name='end_time_to_evaluate',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='time_to_serve',
            new_name='end_time_to_serve',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='time_to_work',
            new_name='end_time_to_work',
        ),
        migrations.AddField(
            model_name='rule',
            name='start_time_to_correct',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='start_time_to_evaluate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='start_time_to_serve',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='start_time_to_work',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
